[package]
name = "simple_server_first"
version = "0.1.0"
authors = ["sufyan <sufyan822@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-server = "0.4.0"
